#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <time.h>
#include <limits.h>

#define NBABIES 5

int babyMaker(int n)
{
	int p, i;
	for(i=0; i<n; i++)
	{
		p = fork();

		if(p<0)
		{
			exit(-1); //ERRO
		}

		if(p==0)
		{
			return i+1; //FILHO i+1
		}
	}
	return 0; //PAI
}

void babyFuneral(int n)
{
	int i, status, exitcode, p;
	for(i=0; i<n; i++)
	{
		p = waitpid(-1,&status,0);

		if(WIFEXITED(status))
		{
			exitcode = WEXITSTATUS(status);
			printf("Baby %d has gone with exit code %d\n", p, exitcode);
		}
	}
}


int main() {

	time_t t;
	srand((unsigned)time(&t));

	int fd[6][2];

	for(int i = 0; i < 6; i++)
	{
		if(pipe(fd[i])==-1)
		{
			perror("Error processing pipes.\n");
			exit(-1);
		}
	}

	int id = babyMaker(NBABIES);

	if(id == 0)
	{
		int random_number = rand() % 5;

		close(fd[0][0]);
		write(fd[0][1],&random_number,sizeof(random_number));
		close(fd[0][1]);

		printf("Number generated by father: %d\n",random_number);

		babyFuneral(NBABIES);

		int toReturn = 0;

		read(fd[5][0],&toReturn,sizeof(toReturn));
		printf("\nFinal Number: %d\n", toReturn);

		printf("Job done. Shutting down...\n");
	}

	else if(id > 0)
	{
		int random_number_child = id;
		int random_number_father = 0;
		int greater = 0;

		read(fd[id-1][0],&random_number_father,sizeof(random_number_father));
		close(fd[id-1][0]);

		if(random_number_child > random_number_father)
		{
			greater = random_number_child;
		}

		else
		{
			greater = random_number_father;
		}

		printf("\nValue random from child: %d \nValue from father: %d \nGreater: %d \n",random_number_child,random_number_father,greater);
		printf("||||||||||||||||||||||||||||||||||||\n");

		close(fd[id][0]);
		write(fd[id][1],&greater,sizeof(greater));
		close(fd[id][1]);

		exit(0);
	}

	else
	{
		printf("error processing childs.\n");
	}

}
